#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/ELP_FULLSCREEN.jar:$APPDIR/lib/core.jar:$APPDIR/lib/fullscreen.jar:$APPDIR/lib/fullscreen_GLsupport.jar:$APPDIR/lib/video.jar" ELP_FULLSCREEN
